import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "@/styles/global.scss";

const font = Lora({
  // style: "italic",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "🏔️ Todo List App 🚀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
